# Generated by Django 5.2.5 on 2025-08-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakePrediction',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_region', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('eq_count_m3_last7d', models.IntegerField(blank=True, null=True)),
                ('eq_count_m4_last30d', models.IntegerField(blank=True, null=True)),
                ('max_mag_last90d', models.FloatField(blank=True, null=True)),
                ('energy_sum_last365d', models.FloatField(blank=True, null=True)),
                ('days_since_last_m5', models.IntegerField(blank=True, null=True)),
                ('gr_b_value_last365d', models.FloatField(blank=True, null=True)),
                ('gr_a_value_last365d', models.FloatField(blank=True, null=True)),
                ('aftershock_rate', models.FloatField(blank=True, null=True)),
                ('dist_to_fault_km', models.FloatField(blank=True, null=True)),
                ('fault_slip_rate_mm_yr', models.FloatField(blank=True, null=True)),
                ('plate_boundary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('depth_to_slab_km', models.FloatField(blank=True, null=True)),
                ('strain_rate', models.FloatField(blank=True, null=True)),
                ('gps_uplift_mm_yr', models.FloatField(blank=True, null=True)),
                ('heat_flow_mw_m2', models.FloatField(blank=True, null=True)),
                ('catalog_completeness_mc', models.FloatField(blank=True, null=True)),
                ('station_density', models.FloatField(blank=True, null=True)),
                ('detection_threshold', models.FloatField(blank=True, null=True)),
                ('prob_m45_next7d', models.FloatField(blank=True, null=True)),
                ('prob_m50_next30d', models.FloatField(blank=True, null=True)),
                ('prob_m60_next90d', models.FloatField(blank=True, null=True)),
                ('label_m45_next7d', models.IntegerField(blank=True, null=True)),
                ('label_m50_next30d', models.IntegerField(blank=True, null=True)),
                ('label_m60_next90d', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prediction',
                'managed': False,
            },
        ),
    ]
