# Generated by Django 5.2.5 on 2025-08-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySummary',
            fields=[
                ('country_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('total_records', models.IntegerField(default=0)),
                ('avg_magnitude', models.FloatField(blank=True, null=True)),
                ('max_magnitude', models.FloatField(blank=True, null=True)),
                ('avg_prob_7d', models.FloatField(blank=True, null=True)),
                ('avg_prob_30d', models.FloatField(blank=True, null=True)),
                ('avg_prob_90d', models.FloatField(blank=True, null=True)),
                ('latest_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
